version: '3'
services:
    server:
        build: ..
        entrypoint: async server
        ports:
            - 8080:8080
            - 8000:8000
    worker:
        build:
            context: ..
            dockerfile: Dockerfile.example
        entrypoint: worker
        environment:
            - 'ASYNC_SERVER_ADDR=async:8080'
            - 'ASYNC_ADVERTISE_ADDR=eth0:8179'
        links:
            - server:async
