FROM golang:alpine AS build

RUN mkdir -p /go/src/github.com/wayt/async
ADD . /go/src/github.com/wayt/async/

RUN cd /go/src/github.com/wayt/async/example/worker && \
    go build -o worker

FROM alpine
COPY --from=build /go/src/github.com/wayt/async/example/worker/worker /usr/bin/worker

# Worker port
EXPOSE 8179

ENTRYPOINT /usr/bin/worker
